### ISSUE TITLE
 Possible mistake in javascript.pest

### ISSUE THREAD

**Issue by Tartasprint** [Kostassoid/memorial#1]
Doing a search about usages of pest, if found that the pest file [memorial-core/src/parser/javascript.pest](https://github.com/Kostassoid/memorial/blob/master/memorial-core/src/parser/javascript.pest) make use of the PUSH operation but never of POP or DROP or PEEK.
I did not investigate whether if this was a mistake or not, but it looks like one and it might result in slower parsing (and useless memory usage).

**Comment by Kostassoid** [comment]
Hi @Tartasprint
I think you're right. I copied this code from some other source and didn't test it properly. Looks like a typo. But also the implementation overall looks a bit naive. I'll work on fixing it soon. Thank you for reporting!

**Comment by Kostassoid** [comment]
FIxed in #2
